### ISSUE TITLE
Corsair H150i Elite RGB resets to default color on boot

### ISSUE THREAD

**Issue by jflevesque** [EvanMulawski/FanControl.CorsairLink#172]
I've just updated to v1.6.0 and noticed that any time FanControl boots, the RGB setting on my pump gets reset to its default value. I've noticed #144 so unsure if its related or not.

**Comment by EvanMulawski** [comment]
Hi @jflevesque, yes, that change was related to #144 and an enhancement is being tracked in #170 to add the ability to specify which default lighting preset it gets reset to (instead of a solid color). In the meantime, you would need to use SignalRGB to have effects or customize the default solid color lighting using the `FANCONTROL_CORSAIRLINK_DIRECT_LIGHTING` [environment variables](https://github.com/EvanMulawski/FanControl.CorsairLink?tab=readme-ov-file#configuration).

**Comment by jflevesque** [comment]
With #170, will that remove the need to use SignalRGB?

**Comment by EvanMulawski** [comment]
Yes. Are you using the default rainbow effect or something else?

**Comment by jflevesque** [comment]
I'm using a simple static color

**Comment by EvanMulawski** [comment]
Oh, then you can just set it using the Windows environment variables right now. For example, this will set the static color to red at 50% brightness:

Name|Value
-|-
FANCONTROL_CORSAIRLINK_DIRECT_LIGHTING_DEFAULT_RGB|255,0,0
FANCONTROL_CORSAIRLINK_DIRECT_LIGHTING_DEFAULT_BRIGHTNESS|50

---

To set these values, start Run or Command Prompt and run `rundll32 sysdm.cpl,EditEnvironmentVariables`. Alternatively, use the `setx` command.

You must restart Fan Control after changing these values.

**Comment by jflevesque** [comment]
Thx, that works very well!
